spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: marcin
    password: marcin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


